app_store_data:
    path: /store
    methods: POST
    controller: App\Controller\StoreController::postAction

app_get_settings:
    path: /settings
    methods: GET
    controller: App\Controller\SettingsController::getAction
