version: '3'
services:
  nginx:
    container_name: epolka-nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ../:/home/www/epolka.local
      - ./nginx/epolka.local.conf:/etc/nginx/conf.d/epolka.local.conf
      - phpsocket:/var/run
    networks:
      localnet:
        aliases:
          - epolka.local
  app:
    container_name: epolka-app
    build: php
    volumes:
      - ../:/home/www/epolka.local
      - phpsocket:/var/run
    networks:
      localnet:
        aliases:
          - epolka.local
  postgres:
    container_name: epolka-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
      - ../docker/postgres:/docker-entrypoint-initdb.d
    networks:
      localnet:
        aliases:
          - epolka.local
volumes:
  phpsocket:

networks:
  localnet:
    driver: bridge
