monolog:
    channels: ["report"]
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!request","!report"]
            file_permission: 0777
        request:
            type: rotating_file
            path: "%kernel.logs_dir%/request/%kernel.environment%.log"
            level: debug
            channels: ["request"]
            max_files: 100
            file_permission: 0777
        report:
            type: rotating_file
            path: "%kernel.logs_dir%/report/%kernel.environment%.log"
            level: debug
            channels: ["report"]
            max_files: 100
            file_permission: 0777
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
            file_permission: 0777
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
