parameters:
    app.host: '%env(APP_HOST)%'
    app.settings.host: '%env(APP_SETTINGS_HOST)%'
    app.settings.alt_host: '%env(APP_SETTINGS_ALT_HOST)%'
    app.settings.default_connection_interval: '%env(int:DEFAULT_CONNECTION_INTERVAL)%'
    app.settings.alt_connection_interval: '%env(int:ALT_CONNECTION_INTERVAL)%'
    app.request_secret: '%env(REQUEST_SECRET)%'
    app.scheme: http
    app.base_url: '%app.scheme%://%app.host%'
    app.var_dir: '%kernel.project_dir%/var/'

    app.report_email_recipients:
        - 'vlyagusha@yandex.ru'
        - 'bondar.s@europos.ru'
        - 'rpurey@gmail.com'
    app.report_email_sender: '%env(APP_EMAIL_SENDER)%'

    app.ftp.username: '%env(FTP_USERNAME)%'
    app.ftp.password: '%env(FTP_PASSWORD)%'
    app.ftp.host: '%env(FTP_HOST)%'
    app.ftp.port: '%env(int:FTP_PORT)%'
    app.ftp.path: '%env(FTP_PATH)%'
    app.ftp.is_passive: '%env(bool:FTP_PASSIVE)%'
